apiVersion: skaffold/v2beta28
kind: Config
deploy:
  # list all file config for cluster
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: formal-fragment-348815
  artifacts:
    # all things is going to be build
    - image: us.gcr.io/formal-fragment-348815/auth
      # - image: thinhbuihong/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        # how to handle changes
        manual:
          - src: "src/**/*.ts"
            dest: .
    # kubectl create secret generic jwt-secret --from-literal JWT_key=thinhdepzai
    # kubectl create secret generic stripe-secret --from-literal STRIPE_KEY=sk_test_51J79rzICDOVuJZn538Bth2zACh4YmZXHW6HkONnLG2nzo0xErcb9dxm383PMMSmylNcrkCi13vrO3pqooV6ieHUY00WROJhkO3
    # - image: thinhbuihong/client
    - image: us.gcr.io/formal-fragment-348815/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        # how to handle changes
        manual:
          - src: "**/*.js"
            dest: .
    # - image: thinhbuihong/tickets
    - image: us.gcr.io/formal-fragment-348815/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        # how to handle changes
        manual:
          - src: "**/*.ts"
            dest: .
    - image: us.gcr.io/formal-fragment-348815/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: us.gcr.io/formal-fragment-348815/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: us.gcr.io/formal-fragment-348815/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
