apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  # list all file config for cluster
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    # all things is going to be build
    - image: thinhbuihong/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        # how to handle changes
        manual:
          - src: "src/**/*.ts"
            dest: .
    # kubectl create secret generic jwt-secret --from-literal JWT_key=thinhdepzai
    # kubectl create secret generic stripe-secret --from-literal STRIPE_KEY=sk_test_51J79rzICDOVuJZn538Bth2zACh4YmZXHW6HkONnLG2nzo0xErcb9dxm383PMMSmylNcrkCi13vrO3pqooV6ieHUY00WROJhkO3
    - image: thinhbuihong/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        # how to handle changes
        manual:
          - src: "**/*.js"
            dest: .
    - image: thinhbuihong/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        # how to handle changes
        manual:
          - src: "**/*.ts"
            dest: .
    - image: thinhbuihong/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: thinhbuihong/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: thinhbuihong/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
