apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  # how to find pods have been created
  template:
    # how to create each of indidual pod
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: thinhbuihong/auth
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-dev-srv:27017/auth"
            - name: JWT_KEY #name for auth container access in env
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_key
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
