apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  # how to find pods have been created
  template:
    # how to create each of indidual pod
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: thinhbuihong/expiration
          env:
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: expiration-redis-srv
