apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  # how to find pods have been created
  template:
    # how to create each of indidual pod
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: thinhbuihong/tickets
          env:
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-srv:27017/tickets"
            - name: JWT_KEY #name for tickets container access in env
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_key
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
